# Generated by Django 2.2 on 2020-06-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_plans_status_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='status_plan',
            field=models.CharField(choices=[(1, 'Pending'), (0, 'completed')], max_length=10),
        ),
    ]
