# Generated by Django 2.2 on 2020-06-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20200627_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='status_plan',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'completed')], max_length=10),
        ),
    ]
