# Generated by Django 2.2 on 2020-06-27 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20200627_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='description_plan',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='plans',
            name='name_plan',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='plans',
            name='status_plan',
            field=models.IntegerField(choices=[(0, 'completed'), (1, 'Pending')], max_length=10),
        ),
    ]
