# Generated by Django 2.2 on 2020-06-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20200627_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='status_plan',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'completed')]),
        ),
    ]
